/**
 * Configuration and physical specifications for the Beneteau 331 Sailboat
 * and the slip with short port finger pier and 4 pilings.
 */

export const KNOTS_TO_MS = 0.514444;
export const MS_TO_KNOTS = 1 / KNOTS_TO_MS;
export const RHO_WATER = 1025; // kg/m^3 (seawater)
export const RHO_AIR = 1.225;  // kg/m^3 (air)

export const BOAT_SPECS = {
  name: "Beneteau 331 (Oceanis 331)",
  loa: 10.34,       // Length Overall: 33' 11" (meters)
  lwl: 9.30,        // Length Waterline: 30' 6" (meters)
  beam: 3.42,       // Beam: 11' 3" (meters)
  draft: 1.65,      // Draft: 5' 5" (meters)
  mass: 5068,       // Displacement: 11,173 lbs (kg)
  inertia: 42000,   // Yaw moment of inertia (kg * m^2)

  // Center of Lateral Resistance (CLR) and Center of Effort (CE) relative to CM (0,0)
  clrOffset: -0.2,  // CLR slightly aft of CM (meters)
  ceOffset: 0.65,   // Windage center of effort forward of CM due to high bow freeboard (meters)
  windageAreaFront: 6.8, // m^2 (frontal profile: hull + cabin + mast)
  windageAreaSide: 24.5, // m^2 (lateral profile: high topsides, cabin trunk, rigging)

  // Beta 25 Marine Diesel Engine
  engine: {
    name: "Beta 25 Inboard Diesel",
    maxHp: 25,
    idleRpm: 850,
    maxRpm: 3200,
    maxThrust: 2800,        // Max forward bollard thrust (Newtons, ~630 lbf)
    reverseThrustRatio: 0.72,// Reverse thrust factor
    propWalkCoeff: 0.28,     // Transverse paddlewheel force ratio in reverse (stern walks to PORT)
    propWashFactor: 2.4,     // Amplification of water velocity over rudder when motoring forward
    rpmResponseRate: 3.2,    // Throttle response smoothness (1/s)
  },

  // Rudder
  rudder: {
    maxAngleDeg: 35,         // Max rudder angle (+/- 35 degrees)
    area: 0.45,              // Rudder blade area (m^2)
    positionY: -4.85,        // Rudder distance aft from CM (meters)
    liftCoeff: 2.8,          // Hydrodynamic lift coefficient
  },

  // Hydrodynamic resistance coefficients (keel & hull)
  hydrodynamics: {
    forwardDrag: 120,        // Forward surge resistance (N / (m/s)^2)
    reverseDrag: 150,        // Reverse surge resistance
    lateralDrag: 1850,       // Immense sideways resistance from fin keel (N / (m/s)^2)
    yawDamping: 45000,       // Resistance to rotational spinning (N*m / (rad/s)^2)
    keelLiftFactor: 16000,   // Lift generated by keel when moving with leeway angle
  },

  // Boat cleat positions relative to Center of Mass (0, 0)
  // X = Starboard (+), Port (-)
  // Y = Bow (+), Stern (-)
  cleats: {
    bow_port: { id: "bow_port", name: "Bow (Port)", x: -0.85, y: 4.65 },
    bow_starboard: { id: "bow_starboard", name: "Bow (Starboard)", x: 0.85, y: 4.65 },
    mid_port: { id: "mid_port", name: "Midship Spring (Port)", x: -1.68, y: 0.20 },
    mid_starboard: { id: "mid_starboard", name: "Midship Spring (Starboard)", x: 1.68, y: 0.20 },
    stern_port: { id: "stern_port", name: "Stern (Port)", x: -1.35, y: -4.80 },
    stern_starboard: { id: "stern_starboard", name: "Stern (Starboard)", x: 1.35, y: -4.80 },
  },

  // Fenders mounted along the port side (where the finger pier is)
  fenders: [
    { name: "Port Bow Fender", x: -1.45, y: 2.8, radius: 0.22 },
    { name: "Port Mid Fender", x: -1.72, y: 0.0, radius: 0.24 },
    { name: "Port Quarter Fender", x: -1.50, y: -3.0, radius: 0.22 },
  ]
};

export const DOCK_CONFIG = {
  // Slip dimensions and coordinate system:
  // Slip runs along Y axis (North/South)
  // Head dock is at Y = 13.0 m
  // Fairway is South at Y < 0 m
  slipCenterlineX: 0,
  slipWidth: 5.4, // Width between pilings (meters, ~17.7 ft)

  // Head dock (main walkway at the top/North)
  headDock: {
    y: 13.0,
    thickness: 2.5,
    minX: -8.0,
    maxX: 8.0,
  },

  // Port-side finger pier extending ~1/3 of the boat length (~3.5 m)
  fingerPier: {
    side: "port",
    startX: -2.7,        // Right edge facing the slip
    width: 1.1,          // Pier width (X goes from -3.8 to -2.7)
    startY: 13.0,        // Attached to head dock
    length: 3.6,         // 3.6 meters long (~11.8 ft, approx 1/3 of Beneteau 331 LOA)
    endY: 9.4,           // Pier terminus
    cleats: [
      { id: "finger_end", name: "Finger Pier Outer End Cleat", x: -2.7, y: 9.55 },
      { id: "finger_mid", name: "Finger Pier Mid Cleat", x: -2.7, y: 11.20 },
      { id: "finger_root", name: "Finger Pier Root Cleat", x: -2.7, y: 12.80 },
    ]
  },

  // Starboard main dock edge / neighbor slip boundary
  starboardBoundaryX: 2.7,

  // Four Pilings ("phones")
  pilings: [
    {
      id: "pile_outer_port",
      name: "Outer Port Piling",
      x: -2.7,
      y: 0.5,
      radius: 0.26,
      cleatX: -2.7,
      cleatY: 0.5,
    },
    {
      id: "pile_outer_starboard",
      name: "Outer Starboard Piling",
      x: 2.7,
      y: 0.5,
      radius: 0.26,
      cleatX: 2.7,
      cleatY: 0.5,
    },
    {
      id: "pile_inner_port",
      name: "Inner Port Piling / Cleat",
      x: -2.7,
      y: 12.8,
      radius: 0.24,
      cleatX: -2.7,
      cleatY: 12.8,
    },
    {
      id: "pile_inner_starboard",
      name: "Inner Starboard Piling / Cleat",
      x: 2.7,
      y: 12.8,
      radius: 0.24,
      cleatX: 2.7,
      cleatY: 12.8,
    }
  ],

  // Extra head dock cleats
  headDockCleats: [
    { id: "head_port", name: "Head Dock Port Cleat", x: -1.2, y: 13.1 },
    { id: "head_starboard", name: "Head Dock Starboard Cleat", x: 1.2, y: 13.1 },
  ]
};

export const MOORING_SPECS = {
  springConstant: 55000,    // N/m (firm dock line base stiffness)
  snubConstant: 220000,     // N/m (exponential snubbing resistance)
  dampingConstant: 7500,    // N*s/m (internal line damping)
  maxStretchRatio: 0.05,    // 5% max stretch before hard mechanical arrest
  maxBreakingStrain: 38000, // N (~8,500 lbf breaking strength for 5/8" nylon line)
};

export const INITIAL_CONDITIONS = {
  approach: {
    x: 0.0,
    y: -4.5,              // Right outside slip mouth (outer pilings at y = 0.5), fully on-screen!
    headingDeg: 0,        // Pointing straight North into slip
    speedKnots: 1.0,
    rudderDeg: 0,
    throttle: 0.20,
  },
  tiedInSlip: {
    x: -0.6,              // Snugged near the port finger pier with fenders
    y: 7.0,               // In slip, bow near head dock, stern inside outer pilings
    headingDeg: 0,
    speedKnots: 0,
    rudderDeg: 0,
    throttle: 0.0,
  }
};
